name: tricorder_zero
description: Tricorder.Zero

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  video_player: ^2.3.0
  flutter_riverpod: ^1.0.3
  flutter_polygon: ^0.3.0+2
  glass: ^1.0.1+1
  go_router: ^3.0.7
  chart_sparkline: ^1.0.10
  syncfusion_flutter_charts: ^20.1.48
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  # ffmpeg_kit_flutter: ^4.5.1
  flutter_blue: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6

flutter_native_splash:
  color: "#000000"
  android: true
  ios: true


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Dameron
      fonts:
        - asset: assets/fonts/dameronital.ttf
    - family: Thicccboi
      fonts:
        - asset: assets/fonts/THICCCBOI-Regular.ttf
        - asset: assets/fonts/THICCCBOI-SemiBold.ttf
          weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
